name: "Push"

on:
  push:
    branches: [main]
  workflow_dispatch:


concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true
  
jobs:
  release-goat:
    name: release-goat
    uses: ./.github/workflows/release.yml
    secrets: inherit
