name: "Release"

on:
  push:
    branches: [main]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  release-docker:
    name: release
    uses: "goat-community/.github/.github/workflows/reusable-docker-build.yml@main"
    permissions:
      contents: read
      packages: write
      pull-requests: write
    secrets:
      dockerhub-username: ${{ secrets.DOCKER_USERNAME }}
      dockerhub-token: ${{ secrets.DOCKER_PASSWORD }}
    with:
      dockerhub-enable: true
      ghcr-enable: false
      push: ${{ github.event_name != 'pull_request' }}
      file: ${{ github.workspace }}/apps/goat/Dockerfile
      image-names: |
        goatcommunity/goat-frontend
